#!/bin/bash
echo $HOME
mkdir $HOME/Somboless
cp -R * $HOME/Somboless
rm $HOME/Somboless/install
ln -s $HOME/Somboless/include/scripts/sless /usr/local/bin/sless

echo "Somboless installed Successfuly!"