#!/bin/bash 
OS=`uname -s`
if [ "$1" = "-nc" ]; 
	then echo “This Is FreeBSD”
# elif [ “$OS” = “CYGWIN_NT-5.1” ]; 
# 	then echo “This is Cygwin”
# elif [ “$OS” = “SunOS” ]; 
# 	then echo “This is Solaris”
# elif [ "$OS" = "Darwin" ]; 
# 	then echo “This is Mac OSX”
# elif [ “$OS” = “AIX” ]; 
# 	then echo “This is AIX”
# elif [ “$OS” = “Minix” ]; 
# 	then echo “This is Minix”
# elif [ “$OS” = “Linux” ]; 
# 	then echo “This is Linux”
# elif [ "$1" = "kfir" ]; 
# 	then echo "yes"
# else
# 	echo “Failed to identify this OS”
fi

echo $OS"lol"

