#!/bin/bash
controller_name=$1

toLower() {
	echo $1 | tr "[:upper:]" "[:lower:]"
}

low=`toLower $controller_name`
file=$low"_controller"

#mkdir ../../controllers
cat $HOME/Somboless/include/scripts/resources/controller.txt | sed "s/repMe/$1/" > "temp.txt"
cat temp.txt | sed "s/repme/$low/" > "controllers/$file.php"
rm temp.txt


